# Generated by Django 5.0.7 on 2025-01-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sendmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254, unique=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='file')),
                ('subject', models.TextField(null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
    ]
