# Generated by Django 5.0.7 on 2025-01-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmail',
            name='file',
            field=models.FileField(upload_to='file/'),
        ),
    ]
